//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelodyShop.DAL
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class Product
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
      this.Carts = new HashSet<Cart>();
    }
    public int id { get; set; }
    [Display(Name = "Nazwa")]
    public string name { get; set; }
    [Display(Name = "Kategoria")]
    public string category { get; set; }
    [Display(Name = "Cena")]
    public decimal price { get; set; }
    [Display(Name = "Szczegóły")]
    public string detail { get; set; }

    public string modyfity { get; set; }
    public string created { get; set; }
    public Nullable<System.DateTime> modyfityDate { get; set; }
    public Nullable<System.DateTime> createdDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
  }
}
